### ISSUE TITLE
MTK bootable

### ISSUE THREAD

**Issue by lingchenckobe** [Ruben1863/android_device_bluboo_maya#1]
Hi Ruben:
Can you share MTK bootable? I only used to study. very thanks!

**Comment by Ruben1863** [comment]
well, this tree is for lineage OS, so mtk botable is not here. But you can find MTK full sources leaks at 4pda forum on "mtk kernel" topic

**Comment by lingchenckobe** [comment]
You give the website which language is not English, I can not understand this.

**Comment by Ruben1863** [comment]
lol, use Google Translate
